// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ6fJ8TTEXx0K13Nd8qc3pp4ccmqxYodY',
    appId: '1:964905576605:web:74f55e8cda949f4d9d8c74',
    messagingSenderId: '964905576605',
    projectId: 'nutri-ia-ded99',
    authDomain: 'nutri-ia-ded99.firebaseapp.com',
    storageBucket: 'nutri-ia-ded99.firebasestorage.app',
    measurementId: 'G-7HFXTQ9M73',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgft01bPomioJARcwdKou0hpkg-9L-nIU',
    appId: '1:964905576605:android:7f0644d75b645fb89d8c74',
    messagingSenderId: '964905576605',
    projectId: 'nutri-ia-ded99',
    storageBucket: 'nutri-ia-ded99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4vqDbxY8-W5yFhiA615JHMKf2nAfrPR4',
    appId: '1:964905576605:ios:126e5fd00353f7bf9d8c74',
    messagingSenderId: '964905576605',
    projectId: 'nutri-ia-ded99',
    storageBucket: 'nutri-ia-ded99.firebasestorage.app',
    iosBundleId: 'com.example.nutriLucasIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4vqDbxY8-W5yFhiA615JHMKf2nAfrPR4',
    appId: '1:964905576605:ios:126e5fd00353f7bf9d8c74',
    messagingSenderId: '964905576605',
    projectId: 'nutri-ia-ded99',
    storageBucket: 'nutri-ia-ded99.firebasestorage.app',
    iosBundleId: 'com.example.nutriLucasIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ6fJ8TTEXx0K13Nd8qc3pp4ccmqxYodY',
    appId: '1:964905576605:web:e4f11d204f8921eb9d8c74',
    messagingSenderId: '964905576605',
    projectId: 'nutri-ia-ded99',
    authDomain: 'nutri-ia-ded99.firebaseapp.com',
    storageBucket: 'nutri-ia-ded99.firebasestorage.app',
    measurementId: 'G-H175GK58R0',
  );
}
