import 'package:flutter/material.dart';
import '../../core/calculators/health_calculator.dart';
import '../../services/nutri_database.dart';

class WizardOnboardingPage extends StatefulWidget { const WizardOnboardingPage({super.key}); @override State<WizardOnboardingPage> createState() => _WizardOnboardingPageState(); }
class _WizardOnboardingPageState extends State<WizardOnboardingPage> {
  final pageController = PageController(); int step = 0; bool loading = false;
  final name = TextEditingController(text: 'Lucas'), lastName = TextEditingController(), age = TextEditingController(text: '33'), birthDate = TextEditingController();
  final weight = TextEditingController(text: '83'), targetWeight = TextEditingController(text: '78'), height = TextEditingController(text: '169'), waist = TextEditingController();
  final wakeTime = TextEditingController(text: '07:00'), sleepTime = TextEditingController(text: '23:00'), mealsTimes = TextEditingController(text: '09h café, 11h almoço, 15h café da tarde, noite jantar');
  final trainingRoutine = TextEditingController(text: 'Academia segunda, terça e quinta. Esteira segunda, quarta e sexta.'), medicines = TextEditingController(text: 'creatina, whey'), healthNotes = TextEditingController(), initialPhotoNotes = TextEditingController(text: 'Foto inicial do corpo para comparar evolução depois.');
  String sex = 'masculino', goal = 'Emagrecer e ganhar massa', activityLevel = 'Leve'; int waterCupMl = 250; bool freeWeekendNight = true, wantsWaterReminder = true, wantsMedicineReminder = true, wantsDailyReport = true;
  final selectedFoods = <String>{'pão','ovos','arroz','frango','carne','batata doce','banana','whey'}; final selectedDrinks = <String>{'água','água com gás','café com leite'}; final dislikedFoods = <String>{'peixe','salada','comida japonesa'};
  final foodOptions = ['pão','ovos','arroz','feijão','frango','carne','batata doce','banana','iogurte','whey','hambúrguer','pizza','batata frita','queijo','requeijão','linguiça','macarrão','aveia','laranja','acerola'];
  final drinkOptions = ['água','água com gás','café','café com leite','leite','suco natural','chá','whey com leite']; final dislikeOptions = ['peixe','salada','comida japonesa','legumes','verduras','leite','frutas','feijão','aveia'];
  double get weightKg => double.tryParse(weight.text.replaceAll(',', '.')) ?? 83; double get targetWeightKg => double.tryParse(targetWeight.text.replaceAll(',', '.')) ?? 78; double get heightCm => double.tryParse(height.text.replaceAll(',', '.')) ?? 169; double get waistCm => double.tryParse(waist.text.replaceAll(',', '.')) ?? 0; int get userAge => int.tryParse(age.text) ?? 33;
  void next(){ if(step<6){setState(()=>step++); pageController.nextPage(duration: const Duration(milliseconds:250), curve: Curves.easeOut);} else {save();}}
  void previous(){ if(step>0){setState(()=>step--); pageController.previousPage(duration: const Duration(milliseconds:250), curve: Curves.easeOut);}}
  Future<void> save() async { setState(()=>loading=true); try{ final bmr=HealthCalculator.bmr(sex: sex, weightKg: weightKg, heightCm: heightCm, age: userAge); final dailyGoal=HealthCalculator.dailyGoal(bmr: bmr, goal: goal, activityLevel: activityLevel); final water=HealthCalculator.waterLiters(weightKg: weightKg); final protein=HealthCalculator.proteinTarget(weightKg: weightKg, goal: goal); final imc=HealthCalculator.bmi(weightKg: weightKg, heightCm: heightCm); await NutriDatabase().completeWizard({'name':name.text.trim(),'lastName':lastName.text.trim(),'age':userAge,'birthDate':birthDate.text.trim(),'sex':sex,'weightKg':weightKg,'targetWeightKg':targetWeightKg,'heightCm':heightCm,'waistCm':waistCm,'goal':goal,'activityLevel':activityLevel,'wakeTime':wakeTime.text.trim(),'sleepTime':sleepTime.text.trim(),'mealsTimes':mealsTimes.text.trim(),'trainingRoutine':trainingRoutine.text.trim(),'likesText':selectedFoods.join(', '),'drinksText':selectedDrinks.join(', '),'dislikesText':dislikedFoods.join(', '),'medicinesText':medicines.text.trim(),'healthNotes':healthNotes.text.trim(),'initialPhotoNotes':initialPhotoNotes.text.trim(),'freeWeekendNight':freeWeekendNight,'wantsWaterReminder':wantsWaterReminder,'wantsMedicineReminder':wantsMedicineReminder,'wantsDailyReport':wantsDailyReport,'waterCupMl':waterCupMl,'bmr':bmr.round(),'dailyGoalCalories':dailyGoal,'waterGoalLiters':water,'proteinGoalGrams':protein,'bmi':imc}); if(waistCm>0 || initialPhotoNotes.text.trim().isNotEmpty){ await NutriDatabase().addBodyProgress(weightKg: weightKg, waistCm: waistCm, notes: initialPhotoNotes.text); } } catch(e){ if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Erro ao salvar: $e'))); } finally{ if(mounted) setState(()=>loading=false); } }
  Widget field(String label, TextEditingController c,{int lines=1})=>Padding(padding: const EdgeInsets.only(bottom:12), child: TextField(controller:c,minLines:lines,maxLines:lines==1?1:5,onChanged:(_)=>setState((){}),decoration:InputDecoration(labelText:label)));
  Widget chips(List<String> options, Set<String> selected)=>Wrap(spacing:8,runSpacing:8,children:[for(final o in options) FilterChip(label:Text(o),selected:selected.contains(o),onSelected:(v)=>setState(()=>v?selected.add(o):selected.remove(o)))]);
  Widget pageTitle(String t,String s)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(s,style:TextStyle(color:Colors.white.withOpacity(.75))),const SizedBox(height:22)]);
  @override Widget build(BuildContext context){ final bmr=HealthCalculator.bmr(sex: sex, weightKg: weightKg, heightCm: heightCm, age: userAge); final dailyGoal=HealthCalculator.dailyGoal(bmr:bmr, goal:goal, activityLevel:activityLevel); final water=HealthCalculator.waterLiters(weightKg:weightKg); final protein=HealthCalculator.proteinTarget(weightKg:weightKg, goal:goal); final imc=HealthCalculator.bmi(weightKg:weightKg, heightCm:heightCm); final diffWeight=weightKg-targetWeightKg;
    return Scaffold(appBar: AppBar(title: const Text('Configuração Inteligente')), body: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth:880), child: Column(children:[
      Padding(padding: const EdgeInsets.fromLTRB(22,14,22,4), child: LinearProgressIndicator(value:(step+1)/7,minHeight:10,borderRadius:BorderRadius.circular(20))),
      Expanded(child: PageView(controller:pageController, physics: const NeverScrollableScrollPhysics(), children:[
        ListView(padding: const EdgeInsets.all(22), children:[pageTitle('Quem é você?','Quanto mais dados, mais exato o Nutri IA fica.'), Row(children:[Expanded(child:field('Nome',name)), const SizedBox(width:12), Expanded(child:field('Sobrenome',lastName))]), Row(children:[Expanded(child:field('Idade',age)), const SizedBox(width:12), Expanded(child:field('Nascimento opcional',birthDate))]), DropdownButtonFormField<String>(value:sex,decoration: const InputDecoration(labelText:'Sexo'),items: const [DropdownMenuItem(value:'masculino',child:Text('Masculino')),DropdownMenuItem(value:'feminino',child:Text('Feminino'))],onChanged:(v)=>setState(()=>sex=v??sex))]),
        ListView(padding: const EdgeInsets.all(22), children:[pageTitle('Corpo e meta','Vamos acompanhar evolução real com peso, medidas e fotos.'), Row(children:[Expanded(child:field('Peso atual kg',weight)), const SizedBox(width:12), Expanded(child:field('Peso desejado kg',targetWeight))]), Row(children:[Expanded(child:field('Altura cm',height)), const SizedBox(width:12), Expanded(child:field('Cintura cm opcional',waist))]), Card(child:Padding(padding: const EdgeInsets.all(18), child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[const Text('Prévia corporal',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),Text('⚖ IMC: ${imc.toStringAsFixed(1)}'),Text(diffWeight>0?'🎯 Faltam perder ${diffWeight.toStringAsFixed(1)} kg':'🎯 Meta de peso configurada'),Text('🔥 Gasto parado: ${bmr.round()} kcal/dia')])))]),
        ListView(padding: const EdgeInsets.all(22), children:[pageTitle('Objetivo e rotina','Aqui nasce o plano personalizado.'), DropdownButtonFormField<String>(value:goal,decoration: const InputDecoration(labelText:'Objetivo principal'),items: const [DropdownMenuItem(value:'Emagrecer',child:Text('Emagrecer')),DropdownMenuItem(value:'Ganhar massa',child:Text('Ganhar massa')),DropdownMenuItem(value:'Emagrecer e ganhar massa',child:Text('Emagrecer e ganhar massa')),DropdownMenuItem(value:'Definição',child:Text('Definição')),DropdownMenuItem(value:'Manter peso',child:Text('Manter peso'))],onChanged:(v)=>setState(()=>goal=v??goal)), const SizedBox(height:12), DropdownButtonFormField<String>(value:activityLevel,decoration: const InputDecoration(labelText:'Nível de atividade'),items: const [DropdownMenuItem(value:'Sedentário',child:Text('Sedentário')),DropdownMenuItem(value:'Leve',child:Text('Leve')),DropdownMenuItem(value:'Moderado',child:Text('Moderado')),DropdownMenuItem(value:'Intenso',child:Text('Intenso'))],onChanged:(v)=>setState(()=>activityLevel=v??activityLevel)), const SizedBox(height:12), Row(children:[Expanded(child:field('Hora que acorda',wakeTime)), const SizedBox(width:12), Expanded(child:field('Hora que dorme',sleepTime))]), field('Horários das refeições',mealsTimes,lines:2), field('Rotina de treino',trainingRoutine,lines:2)]),
        ListView(padding: const EdgeInsets.all(22), children:[pageTitle('Alimentação','O cardápio será feito com o que você gosta e evita.'), const Text('Gosto de comer',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:8),chips(foodOptions,selectedFoods),const SizedBox(height:22),const Text('Gosto de beber',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:8),chips(drinkOptions,selectedDrinks),const SizedBox(height:22),const Text('Não gosto / evito',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:8),chips(dislikeOptions,dislikedFoods)]),
        ListView(padding: const EdgeInsets.all(22), children:[pageTitle('Saúde e lembretes','O Nutri IA vai te lembrar de água, remédios e rotina.'), field('Remédios, vitaminas e suplementos',medicines,lines:3), field('Observações de saúde',healthNotes,lines:3), DropdownButtonFormField<int>(value:waterCupMl,decoration: const InputDecoration(labelText:'Botão padrão de água'),items: const [DropdownMenuItem(value:200,child:Text('Copo 200 ml')),DropdownMenuItem(value:250,child:Text('Copo 250 ml')),DropdownMenuItem(value:300,child:Text('Copo 300 ml')),DropdownMenuItem(value:500,child:Text('Garrafa 500 ml')),DropdownMenuItem(value:750,child:Text('Garrafa 750 ml')),DropdownMenuItem(value:1000,child:Text('Garrafa 1 litro'))],onChanged:(v)=>setState(()=>waterCupMl=v??waterCupMl)), SwitchListTile(value:wantsWaterReminder,onChanged:(v)=>setState(()=>wantsWaterReminder=v),title:const Text('Quero lembrete para tomar água')), SwitchListTile(value:wantsMedicineReminder,onChanged:(v)=>setState(()=>wantsMedicineReminder=v),title:const Text('Quero lembrete de remédios/vitaminas')), SwitchListTile(value:wantsDailyReport,onChanged:(v)=>setState(()=>wantsDailyReport=v),title:const Text('Quero relatório diário'))]),
        ListView(padding: const EdgeInsets.all(22), children:[pageTitle('Evolução corporal','Depois vamos usar fotos para comparar seu corpo com segurança.'), field('Observação da foto inicial',initialPhotoNotes,lines:3), SwitchListTile(value:freeWeekendNight,onChanged:(v)=>setState(()=>freeWeekendNight=v),title:const Text('Liberar besteira controlada sábado e domingo à noite'),subtitle:const Text('O app ajusta o dia para caber pizza, hambúrguer ou lanche sem perder o controle.')), Card(child:Padding(padding: const EdgeInsets.all(18),child:Text('Na próxima sprint vamos adicionar upload de foto de comida e foto corporal usando Firebase Storage.',style:TextStyle(color:Colors.white.withOpacity(.8)))))]),
        ListView(padding: const EdgeInsets.all(22), children:[pageTitle('Resumo final','Seu Nutri IA já nasce personalizado.'), Card(child:Padding(padding: const EdgeInsets.all(18), child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[Text('👤 ${name.text} • $sex • $userAge anos'),Text('⚖ ${weightKg.toStringAsFixed(1)} kg → ${targetWeightKg.toStringAsFixed(1)} kg'),Text('🎯 Objetivo: $goal'),Text('📊 Atividade: $activityLevel'),Text('🔥 Gasto parado: ${bmr.round()} kcal/dia'),Text('🍽 Meta calórica: $dailyGoal kcal/dia'),Text('💧 Água: ${water.toStringAsFixed(1)} L/dia'),Text('🥤 Botão água: $waterCupMl ml'),Text('🍗 Proteína: $protein g/dia'),Text('🍔 Fim de semana livre controlado: ${freeWeekendNight?'sim':'não'}'),Text('📈 Relatório diário: ${wantsDailyReport?'sim':'não'}')])))]),
      ])),
      Padding(padding: const EdgeInsets.fromLTRB(22,10,22,22), child: Row(children:[if(step>0) Expanded(child:OutlinedButton.icon(onPressed:previous,icon:const Icon(Icons.arrow_back),label:const Text('Voltar'))), if(step>0) const SizedBox(width:12), Expanded(child:FilledButton.icon(onPressed:loading?null:next, icon:loading?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):Icon(step==6?Icons.check:Icons.arrow_forward), label:Text(step==6?'Finalizar':'Próximo')))])),
    ]))));
  }
}
